

INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Viru-Nigula naine');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Anseküla naine');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Stiliseeritud riided, ST naised');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Pühalepa mees');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Jüri mees');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Stiliseeritud riided, ST mehed');
INSERT INTO public.costume (id, name) VALUES (DEFAULT, 'Pühalepa naine');

INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Seelik');
 INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Käised');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Vöö');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Põll');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Tanu');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Plisseerseelik');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Tutimüts');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Põll');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Vööpael');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Linane seelik');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Vana lumivalge');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Uus seelik');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Liistik triibuline');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'särk');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Püksid');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Vatt');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Vöö');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Särk');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Kaabu');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Sukad');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Sukapaelad');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Pikk-kuub');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Linased püksid');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Sukapaelad');
  INSERT INTO public.element_type (id, element_type) VALUES (DEFAULT, 'Pärg');

INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 2, 'Anseküla seelik', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 2, 'Anseküla käised', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 3, 'Anseküla vöö', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 4, 'Anseküla põll', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 5, 'Anseküla anu', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 5, 'Plisseerseelik', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 1, 'Karja tutimüts', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 4, 'Karja põll', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 2, 'Stiliseeritud vööpael', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 6, 'Stiliseeritud linane seelik', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 2, 'Vana lumivalge', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 17, 'Uus seelik', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 11, 'Liistik triibuline', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 12, 'Anseküla särk', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 14, 'Anseküla püksid', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 10, 'Anseküla vatt', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 7, 'Anseküla vöö', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 12, 'Anseküla särk', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 19, 'Anseküla kaabu', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 22, 'Anseküla sukad', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 21, 'Sukapaelad', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 6, 'Pikk-kuub', 'mingi kirjeldus');
 INSERT INTO public.element (id, element_type_id, element_name, description) VALUES (DEFAULT, 1, 'Linased püksid', 'mingi kirjeldus');

INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 2);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 3);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 4);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 5);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 6);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 7);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 8);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 9);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 10);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 11);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 5, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 5, 2);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 2, 3);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 3, 4);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 4, 4);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 5, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 3, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 2, 1);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 1, 7);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 4, 7);
INSERT INTO public.element_in_costume (id, costume_id, set_element_id) VALUES (DEFAULT, 2, 7);

